CREATE TABLE BMAUsers (
    UserID UNIQUEIDENTIFIER NOT NULL,
    UserName NVARCHAR(1000) NOT NULL,
    EmailAddress NVARCHAR(1000) NOT NULL,
    DashboardAccess BIT NOT NULL,
    SchoolID UNIQUEIDENTIFIER NULL,
    AccessExpire DATETIME NULL
    PRIMARY KEY (UserID)
);
CREATE TABLE BMASchools (
    ID UNIQUEIDENTIFIER NOT NULL,
    SchoolName NVARCHAR(1000) NOT NULL,
    SchoolAddress NVARCHAR(1000) NOT NULL,
    ImageID UNIQUEIDENTIFIER NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE BMAStudents (
    ID UNIQUEIDENTIFIER NOT NULL,
    SchoolID UNIQUEIDENTIFIER NOT NULL,
    FirstName NVARCHAR(1000) NOT NULL,
    LastName NVARCHAR(1000) NOT NULL,
    EmailAddress NVARCHAR(1000) NOT NULL,
    PhoneNumber NVARCHAR(1000) NULL,
    RankID UNIQUEIDENTIFIER NULL,
    DateAwarded DATETIME NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE BMARanks (
    ID UNIQUEIDENTIFIER NOT NULL,
    RankName NVARCHAR(1000) NOT NULL,
    RankDescription NVARCHAR(1000) NULL,
    OrderNumber INT NOT NULL,
    Color1 NVARCHAR(100) NULL,
    Color2 NVARCHAR(100) NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE BMAStudentRanks (
    ID UNIQUEIDENTIFIER NOT NULL,
    StudentID UNIQUEIDENTIFIER NOT NULL,
    RankID UNIQUEIDENTIFIER NOT NULL,
    DateAwarded DATETIME NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE BMAStudentAttends (
    ID UNIQUEIDENTIFIER NOT NULL,
    StudentID UNIQUEIDENTIFIER NOT NULL,
    AttendDate DATETIME NOT NULL,
    LoggedDate DATETIME NOT NULL,
    LoggedBy UNIQUEIDENTIFIER NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE BMAStudentUsers (
    ID UNIQUEIDENTIFIER NOT NULL,
    UserID UNIQUEIDENTIFIER NOT NULL,
    StudentID UNIQUEIDENTIFIER NOT NULL,
    EditInfo BIT NOT NULL,
    PRIMARY KEY (ID)
);

/*
CREATE TABLE BMASchedule (
    ID UNIQUEIDENTIFIER NOT NULL,
    DayOfWeek INT NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE BMAEvents (
    ID UNIQUEIDENTIFIER NOT NULL,
    EventName NVARCHAR(1000) NOT NULL,
    EventDate DATETIME NOT NULL,
    PRIMARY KEY (ID)
)
*/
